import type { CaseDefinition } from './types'

export const case000: CaseDefinition = {
  id: 'case-000',
  number: '000',
  title: 'O Envelope Azul',
  kicker: 'ARQUIVO INTERNO // 23.09.2026',
  summary: 'Um envelope com R$ 8.000 desapareceu de uma sala controlada por crachá. Três pessoas permaneceram ligadas ao setor no fim do expediente.',
  incidentTime: '19:04',
  amount: 'R$ 8.000',
  people: [
    {
      id: 'marta',
      name: 'Marta Reis',
      role: 'Financeiro',
      summary: 'Responsável pela conferência e pelo fechamento do valor naquele turno.',
      initials: 'MR',
    },
    {
      id: 'andre',
      name: 'André Lima',
      role: 'Administrativo',
      summary: 'Permaneceu no prédio após a saída de Marta.',
      initials: 'AL',
    },
    {
      id: 'caio',
      name: 'Caio Ferreira',
      role: 'Operações',
      summary: 'Disse estar cuidando de demandas da área de carga no fim do expediente.',
      initials: 'CF',
    },
  ],
  initialEvidenceIds: ['incident', 'financial-control', 'access-log', 'marta-statement'],
  evidence: [
    {
      id: 'incident',
      kind: 'document',
      eyebrow: 'REGISTRO DE OCORRÊNCIA // 19:05',
      title: 'Desaparecimento de numerário',
      subtitle: 'Setor financeiro · Sala de acesso controlado',
      body: [
        'Às 19:04, a gerência acessou a sala financeira para recolher um envelope azul contendo numerário do fechamento.',
        'O envelope não estava mais sobre a mesa. A sala possui uma única porta de entrada, liberada por crachá. A saída é feita por botão interno e não gera novo registro de acesso.',
        'Não há câmera no interior da sala.',
      ],
    },
    {
      id: 'financial-control',
      kind: 'document',
      eyebrow: 'CONTROLE FINANCEIRO // FECHAMENTO',
      title: 'Conferência de numerário',
      subtitle: 'Documento interno · Referência 000-18B',
      rows: [
        { Campo: 'Horário da conferência', Valor: '18:31' },
        { Campo: 'Valor', Valor: 'R$ 8.000,00' },
        { Campo: 'Acondicionamento', Valor: 'Envelope azul lacrado' },
        { Campo: 'Responsável', Valor: 'Marta Reis' },
      ],
    },
    {
      id: 'access-log',
      kind: 'access-log',
      eyebrow: 'SEGURANÇA // CONTROLE DE ACESSO',
      title: 'Financeiro — registros da porta',
      subtitle: 'Leitor FIN-01 · saída interna não registrada',
      rows: [
        { Horário: '18:33', Identificação: 'MARTA REIS', Evento: 'ENTRADA AUTORIZADA' },
        { Horário: '18:37', Identificação: 'ANDRÉ LIMA', Evento: 'ENTRADA AUTORIZADA' },
        { Horário: '18:47', Identificação: 'MARTA REIS', Evento: 'ENTRADA AUTORIZADA' },
        { Horário: '19:04', Identificação: 'GERÊNCIA', Evento: 'ENTRADA AUTORIZADA' },
      ],
    },
    {
      id: 'marta-statement',
      kind: 'statement',
      eyebrow: 'DEPOIMENTO // MARTA REIS',
      title: 'Relato inicial',
      subtitle: 'Coletado após a descoberta do desaparecimento',
      personId: 'marta',
      quote: 'Terminei a conferência, fechei a sala e fui embora por volta das 18h35. Não voltei ao financeiro depois disso.',
      body: [
        'Marta afirma ter encerrado a rotina do financeiro antes dos demais funcionários e deixado o prédio logo em seguida.',
      ],
    },
    {
      id: 'cctv-marta-exit',
      kind: 'cctv',
      eyebrow: 'CÂMERA 02 // RECEPÇÃO',
      title: 'Saída principal — 18:35:14',
      subtitle: 'Trecho recuperado do circuito interno',
      body: [
        'O registro mostra Marta atravessando a recepção e deixando o prédio pela saída principal às 18:35:14.',
        'Nos registros seguintes disponíveis até 19:04, Marta não aparece retornando pela entrada principal.',
      ],
      locked: true,
    },
  ],
  timeline: [
    { id: 'money', time: '18:31', label: 'R$ 8.000 conferidos', detail: 'Envelope azul lacrado.', tone: 'neutral' },
    { id: 'marta-fin', time: '18:33', label: 'Marta', detail: 'Acesso ao financeiro.', tone: 'neutral' },
    { id: 'marta-exit', time: '18:35', label: 'Marta sai', detail: 'Câmera 02 confirma a saída.', tone: 'conflict', hiddenUntil: 'marta-exit' },
    { id: 'andre-fin', time: '18:37', label: 'André', detail: 'Acesso ao financeiro.', tone: 'neutral' },
    { id: 'badge', time: '18:47', label: 'Marta?', detail: 'Crachá de Marta abre a porta.', tone: 'question' },
    { id: 'discovery', time: '19:04', label: 'Gerência', detail: 'Envelope não está na sala.', tone: 'neutral' },
  ],
  investigationLines: [
    {
      id: 'marta-exit',
      title: 'Verificar a saída de Marta',
      description: 'Cruzar o depoimento com as câmeras da recepção e da entrada principal.',
      resultTitle: 'Câmera 02 localizada',
      resultBody: 'Há um registro útil às 18:35:14. O material foi adicionado ao arquivo.',
      decisive: true,
    },
    {
      id: 'andre-activity',
      title: 'Revisar a atividade de André',
      description: 'Examinar o acesso das 18:37 e procurar uma inconsistência imediata.',
      resultTitle: 'Linha mantida em observação',
      resultBody: 'O acesso de André às 18:37 já consta no registro. Neste recorte inicial, não há um novo fato verificável que permita explicar o desaparecimento.',
    },
    {
      id: 'loading-area',
      title: 'Revisar a área de carga',
      description: 'Checar se os registros iniciais do setor ajudam a explicar o acesso ao financeiro.',
      resultTitle: 'Sem conclusão neste recorte',
      resultBody: 'Os registros disponíveis nesta etapa não acrescentam uma evidência objetiva sobre quem abriu o financeiro às 18:47.',
    },
  ],
}
